rackspace-infrastructure-automation/aws-terraform-ec2_autorecovery

.circleci/bin/apply.sh, .circleci/bin/check_master.sh, .circleci/bin/destroy.sh, .circleci/bin/lint.sh, .circleci/bin/plan.sh, .circleci/bin/validate.sh, .circleci/config.yml, examples/main.tf, tests/test1/main.tf
This PR sets up testing for the EC2 AutoRecovery module
=> Initial Test Configuration

main.tf, text/amazon_linux_userdata.sh, text/windows_userdata.ps1
added templating to allow more dynamic userdata in the future.
=> update userdata to allow templating

README.md, main.tf, tests/test1/main.tf, variables.tf
This PR adds the 'volume tags' propery (https://www.terraform.io/docs/providers/aws/r/instance.html#volume_tags)
=> Add module parameter for 'volume_tags' resource parameter

README.md, main.tf, text/ubuntu_userdata.sh
- Adds Ubuntu18.04 support to the AR module
- Removes installation of cfn-bootstrap from Ubuntu userdata script
- Adds Readme header to main.tf
=> Initial implementation for Ubuntu 18.04

examples/main.tf, examples/unmanaged.tf, tests/test1/main.tf
PR removes the custom pinning to work around terraform-providers/terraform-provider-aws#6203
=> Update aws provider pinning

README.md, examples/main.tf, examples/unmanaged.tf, main.tf
updated examples and readme with the newest version and readme.
=> update examples and readme

tests/test1/main.tf
updated test to pin to master for tuvok linting soon.
=> updated test to pin to master

README.md, main.tf, tests/test1/main.tf, text/ssm_bootstrap_template.json, variables.tf
Fixes rackspace-infrastructure-automation/aws-terraform-internal#24
Adds variable and local variables to include NFS service installation directly in module.  This will allow for the deployment of an NFS server with minimal effort.
No, this should have no impact to existing resources.
No, change is only to add functionality to this module
Yes Readme has been updated.
No, this change does not affect any existing examples.
=> Add support for NFS service installation

main.tf
https://github.com/rackspace-infrastructure-automation/aws-terraform-internal/issues/215
Updated the 18.04 AMI filter for AMI selection
- if the  AMIs were deployed, instance replacement would be desirable
no
n/a
No
=> Update ubuntu 18.04 AMI filter

examples/custom_cw_agent_config.tf, examples/main.tf, examples/unmanaged.tf
Updating examples
MPCSUPENG-422
- If a bug, describe error scenario, including expected behavior and actual behavior.
- If an enhancement, describe the use case and the perceived benefit(s).
=> updating examples

README.md, examples/custom_cw_agent_config.tf, examples/main.tf, examples/unmanaged.tf, main.tf
-[MPCSUPENG-132](https://jira.rax.io/browse/MPCSUPENG-132)
Adds Windows Server 2019 to list of supported operating systems.
- Adds support for latest Microsoft Operating System
No
No
No variable changes occurred
Examples updated to reflect expected version pinning
=> Add support for Windows Server 2019

README.md, examples/custom_cw_agent_config.tf, examples/main.tf, examples/unmanaged.tf, main.tf, variables.tf
Able to use EBS snapshot for secondary drive.
MPCSUPENG-430
=> adding ability to use ebs snapshot for secondary volume

README.md, main.tf, text/rhel_centos_8_userdata.sh, variables.tf
https://jira.rax.io/browse/MPCSUPENG-723
Added needed sections to add rhel8 capability
- If a bug, describe error scenario, including expected behavior and actual behavior.
- If an enhancement, describe the use case and the perceived benefit(s).
=> added capability for rhel 8

README.md, examples/custom_cw_agent_config.tf, examples/main.tf, examples/unmanaged.tf, main.tf
- https://github.com/rackspace-infrastructure-automation/aws-terraform-internal/issues/235
- https://jira.rax.io/browse/MPCSUPENG-344
removed `cloudformation:Describe*`  from instance policy
- least privilege for the win
no
no
no
no
=> Remove CF specific IAM permission from instance policy

main.tf
https://jira.rax.io/browse/MPCSUPENG-1010
fixes the naming
Naming issues with multi instances
No it shouldn't
no
NA
NA
=> cleaned up multi instance naming

README.md, examples/custom_cw_agent_config.tf, examples/managed.tf, examples/unmanaged.tf, main.tf, tests/test1/main.tf
Update AWS provider >= to 2.7.0 and update README for new provider version as well. Update examples and tests to use the proper provider where needed.
=> Update AWS provider version

README.md, examples/custom_cw_agent_config.tf, examples/main.tf, examples/unmanaged.tf, main.tf
Update example pinnings
Update provide exclusion, as Hashicorp has released a fix for the IP address validation issue <https://github.com/terraform-providers/terraform-provider-aws/pull/13640/files>.
=> Update example pinnings and aws provider exclusion

README.md, examples/custom_cw_agent_config.tf, examples/managed.tf, examples/unmanaged.tf, main.tf, tests/test1/main.tf, variables.tf
- encrypt root volume at launch
- allow KMS CMK for root and secondary volume
https://aws.amazon.com/about-aws/whats-new/2019/05/launch-encrypted-ebs-backed-ec2-instances-from-unencrypted-amis-in-a-single-step/
No
No
Done
No
=> V0.12 root encrypt

README.md, examples/custom_cw_agent_config.tf, examples/main.tf, examples/unmanaged.tf, main.tf, tests/test1/main.tf, variables.tf
- encrypt root volume at launch
- allow KMS CMK for root and secondary volume
https://aws.amazon.com/about-aws/whats-new/2019/05/launch-encrypted-ebs-backed-ec2-instances-from-unencrypted-amis-in-a-single-step/
No
No
Done
No
=> V0.11 root encrypt

README.md, outputs.tf
- AZ output for instances
Request from @toyssan1 
No
No
Yes
No
=> v0.12 - Add AZ output

README.md, examples/custom_cw_agent_config.tf, examples/managed.tf, examples/unmanaged.tf, main.tf, text/rhel_centos_6_userdata.sh, text/rhel_centos_7_userdata.sh, text/rhel_centos_8_userdata.sh, text/ubuntu_userdata.sh
https://jira.rax.io/browse/MPCSUPENG-1360
Fixes RHEL8 bug relating to copy pasta issue.
Cleans up some comment language in the userdata.
Issue with cloudformation stuff in there. Wouldnt let SSM install properly if needed.
If updated yes will trigger destruction/replacement as its userdata.
NA
NA
NA
=> Userdata CFN Bugfix

README.md, examples/custom_cw_agent_config.tf, examples/main.tf, examples/unmanaged.tf, main.tf, text/rhel_centos_8_userdata.sh
Corresponding Issue(s):
https://jira.rax.io/browse/MPCSUPENG-1360
Summary of change(s):
Fixes RHEL8 bug relating to copy pasta issue.
Cleans up some comment language in the userdata.
Reason for Change(s):
Issue with cloudformation stuff in there. Wouldnt let SSM install properly if needed.
Will the change trigger resource destruction or replacement? If yes, please provide justification:
If updated yes will trigger destruction/replacement as its userdata.
Does this update/change involve issues with other external modules? If so, please describe the scenario.
NA
If input variables or output variables have changed or has been added, have you updated the README?
NA
Do examples need to be updated based on changes?
NA
Note to the PR requester about Closing PR's
Please message the person that …
=> Userdata CFN Bugfix for terraform 0.11

README.md, variables.tf
* Fix reference in variables
* Update README to reflect that
=> Update readme for deprecated EC2 SSM role

README.md, main.tf, tests/test1/main.tf, variables.tf
https://jira.rax.io/browse/MPCSUPENG-1465
remove scaleft
yes - tests for no scaleft were removed
no
yes
yes
=> Removing scaleFT install option

README.md, main.tf, tests/test1/main.tf, text/ubuntu_userdata.sh, variables.tf
Corresponding Issue(s):
https://jira.rax.io/browse/MPCSUPENG-1512
Summary of change(s):
Added Ubuntu 20.04
Reason for Change(s):
Requested addition of ubuntu 20.04
Will the change trigger resource destruction or replacement? If yes, please provide justification:
NA new
Does this update/change involve issues with other external modules? If so, please describe the scenario.
no
If input variables or output variables have changed or has been added, have you updated the README?
readme is updated completely
Do examples need to be updated based on changes?
they were updated
Note to the PR requester about Closing PR's
Please message the person that opened the issue when auto closing it on slack, as well as any other stake holders of deep interest. Only close the issue if you believe that the …
=> Add  Ubuntu 20.04 LTS

README.md, main.tf
[MPCSUPENG-2076](https://jira.rax.io/browse/MPCSUPENG-2076)
Updates created SSM document to invoke Rackspace Managed SSM documents from a regional S3 bucket.
Removes the requirement of sharing individual SSM Documents across a large number of accounts.
Yes, SSM document resource will be replaced
No
NA
NA
=> Invoke Rackspace managed SSM documents from regional S3 buckets

README.md, main.tf, text/ubuntu_userdata.sh, variables.tf
[ MPCSUPENG-3353](https://rackspace.atlassian.net/browse/MPCSUPENG-3353)
- Removes EOL'd versions of Ubuntu.
- Updates userdata
Old versions of Ubuntu EOL.
=> Removing EOL versions of Ubuntu.

README.md, variables.tf
[MPCSUPENG-3340](https://rackspace.atlassian.net/browse/MPCSUPENG-3340)
- Removes references to EBS Snapper
EBS Snapper deprecated.
=> Removes references to EBS Snapper

main.tf
- https://www.centos.org/centos-linux-eol/
Removed Centos8
EOL
=> Centos8 is EOL

text/linux_cw_agent_param.json, text/windows_cw_agent_param.json
* Remove custom aggregation on ASG for memory and disk space
* Additional metric for memory
=> CWConfig Updates

main.tf, text/debian_userdata.sh
added debian 10/11 and userdata. tested working.
=> working debian 10/11 

main.tf
-Updated the RHEL7 AMI filter
- old filter was resulting in a empty list on lookup
-No 
- No
- No
- No
=> Update RHEL7 Filter

main.tf
[Issue](https://rackspace.atlassian.net/browse/MPCSUPENG-4592)
- Adds support for Amazon 2022
- New AMI
=> Adds support for Amazon 2022

main.tf, tests/test1/main.tf
Replace Amazon 2022 with 2023
2022 is gone
=> Replace Amazon 2022 with 2023

main.tf
Removing Windows2012 form the different options. [MPCSUPENG-6914](https://rackspace.atlassian.net/browse/MPCSUPENG-6914)
=> Removing Windows 2012
