- examples/main.tf
- examples/unmanaged.tf
- main.tf
- tests/test1/main.tf
- variables.tf
Reference: https://github.com/rackspace-infrastructure-automation/aws-terraform-internal/issues/85 and https://github.com/rackspace-infrastructure-automation/aws-terraform-internal/issues/86
- Bug was caused by EIP resource association being based on the wrong input variable. This has been fixed.
- Also realized that case for EC2 instances without secondary EBS volumes were not being tested. Add test for that case. 
- Fix typo with SSM bootstrapping variables.
> Fix eip allocation issue

- main.tf
- text/amazon_linux_userdata.sh
- text/rhel_centos_6_userdata.sh
- text/rhel_centos_7_userdata.sh
- text/ubuntu_userdata.sh
- text/windows_userdata.ps1
- variables.tf
similar to https://github.com/rackspace-infrastructure-automation/aws-terraform-ec2_asg/pull/8  to keep them alike
adds the ability to do initial and final userdata scripting via a string parameter (single line or multi line). ECS and EKS will be able to add this via an output.
> additional_userdata_update

- .circleci/config.yml
- main.tf
Updates the InstanceID property of the CW Alarms (and updates the EIP resource to match).  As only one 
of the instance lists will ever be empty, we can call `coalescelist` on both, and always get the instance list returned.
Previous value would return "novalue" unexpectedly.
fixes rackspace-infrastructure-automation/aws-terraform-internal#131
> Update CW Alarm dimensions to resolve incorrect instance ID

- .circleci/config.yml
- README.md
- examples/main.tf
- examples/unmanaged.tf
- main.tf
- tests/test1/main.tf
- variables.tf
**WARNING:** This introduces a BC break, as the `ec2_subnet` variable which is currently a `string`, changes to a `list` variable called `subnets`.
The module can still target specific, individual subnets for instance creation if `subnets` is a `list` with only one subnet ID in it.
> Add support for distribution of AR instances across multiple subnets

- main.tf
- tests/test1/main.tf
Fix error when creating 0 instances
Why would anyone want to create zero instances?
Suppose there are templates being re-used for multiple environments, and in a development or test environment, multiple major application roles/functions (let's call them "foo" and "bar") are handled by a single instance to save on costs. In production, however, each major application role lives on its own instance(s) for better resiliency.
Since Terraform doesn't support conditional invocation of modules, specifying an `instance_count` of `0` for "foo" and "bar" in dev/test and an `instance_count` of `1` for "foobar", while specifying an `instance_count` of `1` for "foo" and "bar", respectively, and `0` for "foobar" in Production, would permit reuse across environments and avoid a lot of copy-paste that …
> Support `instance_count = 0`

- outputs.tf
No IP outputs for the AR module so you have to create a data object straight after to be able to create Route53 internal records, which is a typical build requirement to create internal records for all resources that can have them. This should be considered a requirement for enhancing parity between CF and Terraform.
> Add IP outputs to module

- README.md
- tests/test1/main.tf
Reference: https://github.com/rackspace-infrastructure-automation/aws-terraform-internal/issues/170
Add random string to resources to avoid naming collisions.
Also updated incorrect module name in README.
NOTE: Resource destruction is due to a change in tests, not a change module.
> Add random string to resource names

- README.md
- main.tf
- outputs.tf
- tests/test1/main.tf
- variables.tf
https://github.com/rackspace-infrastructure-automation/aws-terraform-internal/issues/122
- Make `image_id` an optional variable
- If `image_id` is not provided, a suitable AMI will be queried using a data resource based on input provided in variable `ec2_os`
- Update README
- Add output for Image ID
- Yes, if Image ID is not manually provided to the module.
- Will cause destruction in tests due to change in tests.
N/A
YES
> Add default AMI mappings and query to module

- README.md
- main.tf
- variables.tf
https://github.com/rackspace-infrastructure-automation/aws-terraform-internal/issues/205
Make use of the default role policy and the default SSM policy optional
No
No
Yes
No, though an advanced example could be added at a later date.
> Make use of default Rackspace and SSM policies optional

- README.md
- main.tf
- variables.tf
https://github.com/rackspace-infrastructure-automation/aws-terraform-internal/issues/206
Adds a control variable to enable or disable the recovery alarms, allowing creation of instance types that do not support recovery actions.
No, default is to retain the alarms.  If control variable is changed, alarms would be destroyed.
No
Yes, readme updated.
No
> Add enable_recovery_alarms parameter to allow disabling recovery alarms

- README.md
- examples/custom_cw_agent_config.tf
- examples/main.tf
- examples/unmanaged.tf
- main.tf
- tests/test1/main.tf
- variables.tf
https://github.com/rackspace-infrastructure-automation/aws-terraform-internal/issues/191
Update `status_check_failed_system_alarm_ticket`, `status_check_failed_instance_alarm_ticket`, and `cpu_alarm_high` CloudWatch alarms to use the CloudWatch Alarm module.
Removed unused random string resource
Yes, change causes replacement of CloudWatch alarms.
No
Yes, readme updated
No
> Implement CloudWatch Alarm Module

- main.tf
- text/ssm_bootstrap_template.json
https://github.com/rackspace-infrastructure-automation/aws-terraform-internal/issues/218
- Adds new SSM document  that is run first in the executiuon order.  As designed it will block until cloud-init  and systemd( where applicable), have completed their runs
No.
No.
No and No
No
> Add a busy wait ssm document

- README.md
- examples/custom_cw_agent_config.tf
- examples/main.tf
- examples/unmanaged.tf
- main.tf
- tests/test1/main.tf
[MPCSUPENG-297](https://jira.rax.io/browse/MPCSUPENG-297)
Updates AMI Filters to allow setting additional custom filters per OS.  Adds initial filters to limit CentOS AMIs to expected product codes.
- Build errors for CentOS 7 due to AMI with expected name but unexpected product code.
No
No
Yes, Readme updated
Yes examples updated
> Update default AMI filter to allow custom filters

- text/rhel_centos_6_userdata.sh
- text/rhel_centos_7_userdata.sh
- text/ubuntu_userdata.sh
None
Remove `exit 0` when SSM is found in CentOS, RHEL7 and Ubuntu userdata text files
The exit stops the final userdata commands running if SSM happens to be found
No
No
N/A
No
> Remove userdata exit 0's when SSM is found because it blocks final cmds

- text/ubuntu_userdata.sh
n/a
Adding DEBIAN_FRONTEND to userdata
Some package installs may prompt  input.  Adding this change suppresses that.
no
no
no
> Ensure dpkg does not not prompt for input

- README.md
- examples/custom_cw_agent_config.tf
- examples/main.tf
- examples/unmanaged.tf
- main.tf
- outputs.tf
- tests/test1/main.tf
- variables.tf
N/A
- general formatting to start aligning to standards
- old `windows` testing logic did not take into account changing to per Windows release years
Using a windows* flavour would not result in correct CW agent params.
Should only update CW agent SSM parameter
No
Done
Done
> Fix logic for testing if var.ec2_os is windows*

- main.tf
* The SSM Managed EC2 policy is now broken up into 4 individual policies. Being a generic module, this change makes the permissions the same as what they were with the previous managed policy.
* This change was tested by manually running the tests included within this module repository
> Address Deprecated AWS Managed Policies

- README.md
- main.tf
- tests/test1/main.tf
- text/managed_ssm_steps.json
- text/ssm_bootstrap_template.json
- variables.tf
* Add variable for making ScaleFT agent installation optional
* Remove ScaleFT from the main SSM bootstrap portion and make it an optional portion similar to the codedeploy segment
* Update readme with new variable description
* Update tests to assert a build with ScaleFT agent will run properly
Yes
* Manually setup module on a test account and verified that the ScaleFT installation step was not included in the SSM command doc steps when disabled, and included when enabled
* Ran test terraform files with new module
> Optional installation of ScaleFT agent

- README.md
- main.tf
- variables.tf
https://jira.rax.io/browse/MPCSUPENG-917
- Remove all Windows 2008 references. 
maintenance to keep pace with supported  OSes.
No. If you are using Windows 2008 then you  should not upgrade to this version of the module.
No.
Yes.
No.
> Remove Windows 2008 references since its EOL

- README.md
- examples/custom_cw_agent_config.tf
- examples/managed.tf
- examples/unmanaged.tf
- main.tf
- outputs.tf
- tests/test1/main.tf
- variables.tf
- https://jira.rax.io/browse/MPCSUPENG-369
- https://github.com/rackspace-infrastructure-automation/aws-terraform-internal/issues/236
- https://jira.rax.io/browse/MPCSUPENG-1015
- https://github.com/rackspace-infrastructure-automation/aws-terraform-internal/issues/283
- enhancement: add internal route53 record creation support
- bugfix.  Remove MOTD meant only for ASG instances
- feature parity
- standards request
- bugfix:  Remove MOTD meant only for ASG instances
no
no
yes
no
> adding r53 internal records support

- README.md
- examples/custom_cw_agent_config.tf
- examples/managed.tf
- examples/unmanaged.tf
- main.tf
- tests/test1/main.tf
- [MPCSUPENG-962](https://jira.rax.io/browse/MPCSUPENG-962)
Updates default inline IAM policy for EC2 instances to only allow access to buckets beginning with `rackspace-`. This will allow access to predetermined S3 files, and if additional S3 locations are required, a managed policy can be assigned to the instances IAM role via existing parameters.
No
No
No variable or output changes.  Version pinning in readme and examples updated.
Version pinning in readme and examples updated.
> Update inline IAM policy for EC2 instances

- main.tf
- tests/test1/main.tf
https://jira.rax.io/browse/MPCSUPENG-1306
- updated the private_ip parameter for both instance types due to new validations in aws provider 2.65.0 https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2650-june-04-2020
- reordered instance resource blocks to align with whats needed
Bug due to empty list when validating against the input
Shouldnt because of evaluation.
Just the newer provider if used.
Did not change
nope
> terraform provider issue

- README.md
- main.tf
- tests/test1/main.tf
- [MPCSUPENG-1306](https://jira.rax.io/browse/MPCSUPENG-1306)
Adds an aws provider declaration, to force the use of a version prior to 2.65.0, when the erroneous private IP address validation was introduced.  This can be removed or adjusted, if\when the error is resolved.
The declared provider is never used in the module, so will not cause issues related to orphaned providers.
Tested with AWS provider pinnings of:
- `version = "~> 1.2"`
- `version = "~> 2.2"`
- See above
No
No
Yes
No
> Limit aws provider to 2.64.0

- examples/custom_ami.tf
- examples/managed.tf
- main.tf
- text/rhel_centos_8_userdata.sh
* Update all mappings to add it
* Update userdata to utilize dnf ssm agent installation
* Update CentOS 7/8 to use new official AMI account
* Remove product code check for CentOS7 since it's no longer coming from marketplace
* Update example to use tmux instead of bind and bind utils as the later has inconsistent naming across OS families and versions
>  Support CentOS 8

- main.tf
- text/ubuntu_userdata.sh
- [MPCSUPENG-970](https://jira.rax.io/browse/MPCSUPENG-970)
- Updates Ubuntu user data script to use the snap tool for SSM installation on ubuntu 16.04 when available
- Updates Ubuntu user data script to always use the snap tool for SSM installations on Ubuntu 18.04 and higher versions
- Updates aws_instance resource to ignore changes to the user data script.  This should ensure that existing instances are not accidentally replaced due to future userdata changes, and should have no impact to newly created instances.
- Better support for later features of Ubuntu distros, and better feature parity with CloudFormation based deployments.
No
No
Not changed
No
Please message the person that opened the issue when auto closing it on slack, as well as any other stake holders of deep interest. Only …
> Update Ubuntu Userdata script to support snap

- main.tf
Adding support for Windows2022
https://rackspace.atlassian.net/browse/MPCSUPENG-3030
Added support for Windows 2022
> Adding support for Windows2022

- text/linux_cw_agent_param.json
Internally sourced from RS support teams.
- The renaming of this metric was a hold over from a product that is no longer used at Rackspace, that for whatever reason had issues with the default AWS config. This is no longer the case and the metric has been set back.
Request from RS Support
> Memory collection metric set back to default.

- README.md
- examples/custom_cw_agent_config.tf
- main.tf
- `template_file` should no longer be used. `templatefile` function has replaced it.
[MPCSUPENG-2862](https://rackspace.atlassian.net/browse/MPCSUPENG-3862)
`data template_file` is deprecated. `templatefile` function has replaced.
Newer versions of TF do not have support for `template_file` especially if you are using a Mac with an M1 chip. The ARM version of TF will stop working if you are using versions higher than 0.15
It did not during tests.
Yes. Updated.
Screenshots
> Remove deprecated `template_file` usage

- README.md
- main.tf
- Remove provider block, according to [here](https://developer.hashicorp.com/terraform/language/meta-arguments/module-providers#default-behavior-inherit-default-providers) the module will get the region configuration from the parent modules that is calling it.
- Tested in local env
- Also changed the name of Centos 7, it was causing the pipeline to fail due that it was not able to find the image.
> Fixed provider bug and centos fix
